# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc ""
  homepage ""
  version "0.1.34"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/clio/releases/download/v0.1.34/clio_0.1.34_Darwin_x86_64.tar.gz"
    sha256 "738f3c2f98d75790422d4df7b65c961ee9920a5eaa01d91554f7cf71e1a8ab63"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/clio/releases/download/v0.1.34/clio_0.1.34_Linux_x86_64.tar.gz"
      sha256 "9ed0afe74384d50d40fb55d9d3c276c45f91de0b4b269aef66d6a310120cd52b"
    end
  end

  def install
    bin.install "clio"
  end
end
