# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc ""
  homepage ""
  version "0.1.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/clio/releases/download/v0.1.17/clio_0.1.17_Darwin_x86_64.tar.gz"
    sha256 "3166144369c0e06daf91003226ba0384953bdbc5eed09f4cb208edcfe17df781"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/clio/releases/download/v0.1.17/clio_0.1.17_Linux_x86_64.tar.gz"
      sha256 "6e24d84c1baa460b52d93f85f5828bb7e93be11e28646704801bd27abc52f88f"
    end
  end

  def install
    bin.install "clio"
  end
end
