# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTap < Formula
  desc ""
  homepage ""
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/jim/releases/download/v0.3.0/jim_0.3.0_darwin_amd64.tar.gz"
    sha256 "4af54f61884073cde976814cc9efe221a7ce758ab64ad074c5c1c9067d252002"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/jim/releases/download/v0.3.0/jim_0.3.0_linux_amd64.tar.gz"
      sha256 "092a6c9e09e02815be87858eccb4b370e921559bb44b0d8240152afbe81ab8aa"
    end
  end

  def install
    bin.install "jim"
  end
end
