# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTap < Formula
  desc ""
  homepage ""
  version "1.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/grift/releases/download/v1.5.0/grift_1.5.0_darwin_amd64.tar.gz"
    sha256 "e555cc66aa9e9e019f8151f7fbc8d193b5de08568544d6c440c5ecbd07c47137"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/grift/releases/download/v1.5.0/grift_1.5.0_linux_amd64.tar.gz"
      sha256 "21bf6ee68c962707fd3f9b2c8a5af099a57acdb13737ce765a8220e29126d3ff"
    end
  end

  def install
    bin.install "grift"
  end
end
