# This file was generated by GoReleaser. DO NOT EDIT.
class Pkger < Formula
  desc ""
  homepage ""
  version "0.12.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/pkger/releases/download/v0.12.1/pkger_0.12.1_darwin_amd64.tar.gz"
    sha256 "267ad3d897c37edf865de056d07dbb6f9ab498648262313b69442f9231aa98aa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/pkger/releases/download/v0.12.1/pkger_0.12.1_linux_amd64.tar.gz"
      sha256 "e1f5450e83c8b8c6122204446c90dc2a241b1fe9807a2d585ab8cb37efcf97cf"
    end
  end

  def install
    bin.install "pkger"
  end
end
