# This file was generated by GoReleaser. DO NOT EDIT.
class Pkger < Formula
  desc ""
  homepage ""
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/pkger/releases/download/v0.4.0/pkger_0.4.0_darwin_amd64.tar.gz"
    sha256 "b581aeb9d26c8e4efa2daaf158a87befe36b4734ab2de6178f1ae351a9f525e4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/pkger/releases/download/v0.4.0/pkger_0.4.0_linux_amd64.tar.gz"
      sha256 "df7fffe39ccde7be9999c6f0ce7d2a28ca11972f9f62cfe37ee5ecd6e007bd9c"
    end
  end

  def install
    bin.install "pkger"
  end
end
