# This file was generated by GoReleaser. DO NOT EDIT.
class Pkger < Formula
  desc ""
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/pkger/releases/download/v0.2.0/pkger_0.2.0_darwin_amd64.tar.gz"
    sha256 "b7456b399184179436ee9cd458b29563031955b1b4743fbebfec681799c61b10"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/pkger/releases/download/v0.2.0/pkger_0.2.0_linux_amd64.tar.gz"
      sha256 "2dd7f2e535e77fd7aaa8494a78ee4023033cc5ca61bfc47c2a5356bf87aa9134"
    end
  end

  def install
    bin.install "pkger"
  end
end
