# This file was generated by GoReleaser. DO NOT EDIT.
class Refresh < Formula
  desc ""
  homepage ""
  version "1.9.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/refresh/releases/download/v1.9.0/refresh_1.9.0_Darwin_x86_64.tar.gz"
    sha256 "ec1751ea00441942e033af0f33304695394d4abb96bd28f06b319c7e2f8c9b4b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/refresh/releases/download/v1.9.0/refresh_1.9.0_Linux_x86_64.tar.gz"
      sha256 "225089eeceb615c86ebd9d96e5d538280b454768919a74606ef354a262e7fc28"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/markbates/refresh/releases/download/v1.9.0/refresh_1.9.0_Linux_arm64.tar.gz"
        sha256 "316c9cedbf18eba5abe89802a6b3ed1e261beb90cd75258a78098397a6a91ca1"
      else
        url "https://github.com/markbates/refresh/releases/download/v1.9.0/refresh_1.9.0_Linux_armv6.tar.gz"
        sha256 "2d5f193861458b1b8c16547c6f33f93fdb8f2398068867fbce3d29ad835e0140"
      end
    end
  end

  def install
    bin.install "refresh"
  end
end
