# This file was generated by GoReleaser. DO NOT EDIT.
class Refresh < Formula
  desc ""
  homepage ""
  version "1.10.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/refresh/releases/download/v1.10.0/refresh_1.10.0_Darwin_x86_64.tar.gz"
    sha256 "30c92c92d3bbbf40a2eec546002b4dfd3fa8851c1e2bc6e1be8f58531edb41d2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/refresh/releases/download/v1.10.0/refresh_1.10.0_Linux_x86_64.tar.gz"
      sha256 "58df3cc5d12e67cc328d344eac344111dac92e62158b7f38049466a3bb1b1c0b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/markbates/refresh/releases/download/v1.10.0/refresh_1.10.0_Linux_arm64.tar.gz"
        sha256 "b24271dedb77374d636f300bb134a8bb2ca545872867db7a9183e35f2d7d0f9e"
      else
        url "https://github.com/markbates/refresh/releases/download/v1.10.0/refresh_1.10.0_Linux_armv6.tar.gz"
        sha256 "33b71e58c470bc8ae15e46a124eda59893adca3b0f113f36982acd89f21b7afb"
      end
    end
  end

  def install
    bin.install "refresh"
  end
end
